### ISSUE TITLE
My HDMI does not work both to my internal screen

### ISSUE THREAD

**Issue by briangtn** [s-light/ASUS-ZenBook-Pro-Duo-UX581GV#10]
My HDMI port only work if I disable my internals screen, I think the problem is my xorg configuration if it's work for you can you give me your xorg.conf file ?

**Comment by s-light** [comment]
just a note:
my HDMI port only works if i have the graphic-card activated.
if only the cpu-internal graphics are active the hdmi port *seems dead*
