### ISSUE TITLE
Ubuntu 20.04 - no wifi

### ISSUE THREAD

**Issue by s-light** [s-light/ASUS-ZenBook-Pro-Duo-UX581GV#11]
I installed Ubuntu 20.04 and no wifi receiving lol

_Originally posted by @Agrover112 in https://github.com/s-light/ASUS-ZenBook-Pro-Duo-UX581GV/issue_comments/711417380_

**Comment by s-light** [comment]
i did an update to 20.04 some time ago (no fresh install)
and for me wifi is working fine.

did you try or searched in any direction on this?
for example if there are others with [similar  problems on different systems](https://askubuntu.com/questions/tagged/20.04+wireless)?

**Comment by Agrover112** [comment]
Issue solved did a fresh install of Ubuntu 20.04 . It worked . But now I'm reinstalling Kubuntu as there is lot known about Kubuntu here. @s-light

**Comment by s-light** [comment]
good you could solve it!

so i will close this!
