### ISSUE TITLE
missing out on power-profiles-daemon?

### ISSUE THREAD

**Issue by anonsquest** [s-light/ASUS-ZenBook-Pro-Duo-UX581GV#19]
For those of you relying on plippo's screenpad kernel patch, are you able to update to the latest kernel and able to use power profiles daemon? I did a fresh install on my system and it seems that his patch no longer works.

**Comment by s-light** [comment]
what exactly are you meaning?
how can i check?
(for me it seems to work all fine.)
```
Kubuntu
20.04.3 LTS (Focal Fossa)
5.4.0-91-generic
```

**Comment by anonsquest** [comment]
Disregard, I was able to solve the issue by doing this:
https://github.com/Plippo/asus-wmi-screenpad/issues/28#issuecomment-974485702

Previously, I did not have access to the updated power-setting options (https://gitlab.freedesktop.org/hadess/power-profiles-daemon) where you toggle between performance - balanced - power saver. 

Now with the above fix, I do.

**Comment by s-light** [comment]
so this can be  closed?
