### ISSUE TITLE
HDMI output not working?

### ISSUE THREAD

**Issue by asicguy** [s-light/ASUS-ZenBook-Pro-Duo-UX581GV#8]
Has anyone had luck using the HDMI output?
I'm currently using thunderbolt to connect to my monitor, however, I need to free up my thunderbolt port to connect a thunderbolt to PCIe connector for FPGA development.
I've tried wayland and X with integrated graphics as well as nvidia (I'm using Ubuntu 18.04) and both detect the monitor correctly, but nothing displays and the monitor goes to sleep. 
The monitor is a 4K/ 60Hz on HDMI and thunderbolt.

**Comment by s-light** [comment]
i did not test it yet! -
but can do so at the weekend. i will let you know!

**Comment by asicguy** [comment]
Switching to lightdm I got the screen to light up on the login screen. It went dark when I logged in then the GUI froze. I was able to switch to a console and uninstall lightdm, reboot and I was back to how things were previously.

Eager to hear if you find anything.

**Comment by s-light** [comment]
i just tested it:
- running system 
- connected monitor 
- `Display` GUI configuration
- monitor was correctly recognized 
- just needed to enable it and move to desired location (display-arrangement)
- after unplugging i had to disable it in the config dialog to get my desktop to 'forget about the screen'

so all in all for me its working fine!

my configuration:
- Kubuntu 19.10
- nvidia drivers 435.21
- LG 4K screen

(you can check your current used drivers with `lshw -c video` and with `nvidia-smi` the nvidia version)

**Comment by asicguy** [comment]
Thanks for trying it. I guess I'll wait for the 20.04 release and see if I have better luck.

**Comment by Agrover112** [comment]
@asicguy  Hey can you tell me if you are using Ubuntu 20.04 and what all functionalities are working for you?

**Comment by asicguy** [comment]
?I haven't upgraded it yet since I've been working from home and need to run windows on it to access work. Sorry.

________________________________

**Comment by symphonymarie** [comment]
> @asicguy Hey can you tell me if you are using Ubuntu 20.04 and what all functionalities are working for you?

I had kububtu running smoothly until the update and now keep running into driver issues every time I reboot. Blacklisted nouveau etc etc but yeah it started acting weird with the HDMI cable so I assume something funny is going on with the Nvidia card. Temporarily running off windows as I was tired of debugging. If anyone has resolved a similar issue I'm open to suggestions!
